export const allCaseStudies = [
  {
    slug: "bath-private-hospital-ahu-refurbishment",
    title: "Private Hospital Bath, Operating Theatre AHU Refurbishment",
    headline: "Operating Theatre AHU Refurbishment with EC Upgrade",
    sector: "Healthcare",
    location: "Bath",
    image: "/private-hospital-bath-case-study.webp",
    summary:
      "BVS refurbished an AHU supplying operating theatres at a private hospital in Bath, EC fans, custom cubic heat exchanger, and new fan bulkheads delivered energy savings with minimal clinical disruption.",
    tags: ["AHU Refurbishment", "EC Fan", "Healthcare"],
    relevantIf: [
      "Theatre or clinical-grade air quality standards are required throughout",
      "Energy reduction is part of the refurbishment brief",
      "Works must fit around a live clinical programme",
    ],
    pdfUrl: "/case-studies/Bath-Private-Hospital-AHU-Refurbishment-Case-Study.pdf",
    services: ["refurbishment", "ec-fan"],
  },
  {
    slug: "nhs-hammersmith-ahu-refurbishment",
    title: "NHS Hammersmith & Fulham, AHU Refurbishment",
    headline: "NHS Trust AHU Refurbishment, Live Facility",
    sector: "Healthcare",
    location: "Hammersmith, London",
    image: "/nhs-hammersmith-fulham-case-study.webp",
    summary:
      "BVS carried out a targeted light refurbishment of AHUs at an NHS hospital in Hammersmith & Fulham, drivebelts, filters, coil cleaning, corrosion treatment, and bathroom extract fan repairs.",
    tags: ["AHU Refurbishment", "NHS", "Healthcare"],
    relevantIf: [
      "Your AHU is in a live clinical facility that stays operational during works",
      "You need targeted component repair rather than full unit replacement",
      "Reliability and indoor air quality cannot be compromised",
    ],
    pdfUrl: "/case-studies/NHS-Hammersmith-Fulham-AHU-Refurbishment-Case-Study.pdf",
    services: ["refurbishment"],
  },
  {
    slug: "friary-meadow-ahu-replacement",
    title: "Friary Meadow Retirement Village, AHU Replacement",
    headline: "AHU Replacement, Continuously Occupied Retirement Village",
    sector: "Healthcare",
    location: "UK",
    image: "/friary-meadow-case-study.webp",
    summary:
      "BVS designed and installed a replacement AHU at Friary Meadow Retirement Village, delivering reliable ventilation for a sensitive residential care environment with minimum disruption to residents.",
    tags: ["AHU Replacement", "Residential Care"],
    relevantIf: [
      "The building is continuously occupied and cannot be vacated for works",
      "Resident comfort and air quality must be maintained throughout",
      "A standard catalogue replacement is not available or suitable for the space",
    ],
    pdfUrl: "/case-studies/Friary-Meadow-Retirement-Village-Case-Study.pdf",
    services: ["manufacturing"],
  },
  {
    slug: "warner-leisure-hotel-gunton-hall-ahu",
    title: "Warner Leisure Hotel Gunton Hall, AHU Manufacturing",
    headline: "Custom AHU Manufactured & Installed, Hotel Pool Hall",
    sector: "Hotel",
    location: "Norfolk",
    image: "/warner-hotel-gunton-case-study.webp",
    summary:
      "BVS designed, manufactured, and installed a custom-built replacement AHU for Warner Leisure Hotel's Gunton Hall swimming pool, tailor-made for a constrained plantroom, delivered in flatpack, and commissioned with a Trend controls panel.",
    tags: ["AHU Manufacturing", "Hotel", "Pool Hall"],
    relevantIf: [
      "Restricted plantroom access prevents a standard unit being delivered whole",
      "End-of-life AHU in a pool hall or glazed, humid environment",
      "You need full scope: design, manufacture, install, and commission under one contract",
    ],
    pdfUrl: "/case-studies/Warner-Leisure-Hotel-Gunton-Hall-Case-Study-.pdf",
    services: ["manufacturing"],
  },
  {
    slug: "marriott-forest-of-arden-pool-ventilation",
    title: "Marriott Forest of Arden, Swimming Pool AHU Troubleshooting",
    headline: "Pool Hall AHU Troubleshooting & Survey, Marriott",
    sector: "Hotel",
    location: "Forest of Arden",
    image: "/warner-hotel-forest-of-arden-case-study.webp",
    summary:
      "The AHU at Marriott Forest of Arden's swimming pool was designed to maintain 31°C but had only ever reached 24°C. BVS validated the system, identified ductwork leaks and AHU configuration faults, and delivered a full remediation scope.",
    tags: ["AHU Troubleshooting", "Hotel", "Pool Hall"],
    relevantIf: [
      "Your pool hall AHU is failing to reach target temperature or humidity",
      "The unit was recently installed or maintained but is still underperforming",
      "You want an independent assessment before committing to replacement",
    ],
    pdfUrl: "/case-studies/Marriott-Hotel-Forest-of-Arden-Troubleshooting-Solutions-Case-Study-x-3-1.pdf",
    services: ["refurbishment"],
  },
  {
    slug: "leisure-centre-dorset-ec-fan-upgrade",
    title: "Leisure Centre Dorset, Swimming Pool AHU EC Fan Upgrade",
    headline: "EC Fan Retrofit, Swimming Pool AHU",
    sector: "Leisure",
    location: "Dorset",
    image: "/dorset-leisure-centre-case-study.webp",
    summary:
      "BVS replaced failed belt-driven fans on a Dorset leisure centre's swimming pool AHU with two Ziehl-Abegg GR561-ZID EC fans, restoring airflow, humidity control, and protecting the building fabric.",
    tags: ["EC Fan Upgrade", "Leisure", "Pool Hall"],
    relevantIf: [
      "Belt-driven fans in a pool hall or humid environment have failed or are near failure",
      "Humidity and temperature control has been lost or is unreliable",
      "You want to extend AHU life without a full casing replacement",
    ],
    pdfUrl: "/case-studies/Case-Study-Leisure-Centre-Dorset-EC-Fan-Upgrade.pdf",
    services: ["ec-fan"],
  },
  {
    slug: "ringwood-leisure-ahu-controller-upgrade",
    title: "Ringwood Leisure Centre, AHU Controller Upgrade",
    headline: "Controller Upgrade: £100k AHU Replacement Avoided",
    sector: "Leisure",
    location: "Ringwood",
    image: "/ringwood-leisure-center-case-study.webp",
    summary:
      "Advised that two AHUs needed full replacement at £100k+, BVS identified the actual cause as failing controls. Trend controllers were installed on both units at a fraction of replacement cost.",
    tags: ["Controller Upgrade", "Leisure", "Trend"],
    relevantIf: [
      "You've been advised to replace AHUs that appear structurally sound",
      "Controls are failing but the mechanical structure of the unit is in good condition",
      "You want an independent assessment before committing to capital expenditure",
    ],
    pdfUrl: "/case-studies/Case-Study-Ringwood-Leisure-AHU-Controls.pdf",
    services: ["controller"],
  },
  {
    slug: "gresham-street-office-ahu-refurbishment",
    title: "10 Gresham Street London, AHU Refurbishment",
    headline: "Full Internal Refurbishment, City Office AHU",
    sector: "Commercial",
    location: "London",
    image: "/gresham-street-office-case-study.webp",
    summary:
      "The AHU at a Gresham Street commercial office in London required full internal refurbishment to meet reduced air volume requirements. BVS replaced all major components and upgraded to a modern inverter and fan assembly.",
    tags: ["AHU Refurbishment", "Commercial", "London"],
    relevantIf: [
      "Multiple internal components have reached end of life at the same time",
      "Air volume requirements have changed since the original installation",
      "You need a complete strip-out and recommission rather than piecemeal repair",
    ],
    pdfUrl: "/case-studies/Gresham-Street-Office-AHU-Refurbishment-Case-Study.pdf",
    services: ["refurbishment", "coil"],
  },
  {
    slug: "pembroke-offices-ahu-refurbishment",
    title: "Pembroke Offices, AHU Refurbishment",
    sector: "Commercial",
    image: "/pembroke-offices-case-study.webp",
    summary:
      "Post front-of-house renovation, BVS refurbished the AHUs at Pembroke Offices, reverse cycle coil, three Ziehl EC fans, 84kW heater batteries, casing repairs, and improved filtration.",
    tags: ["AHU Refurbishment", "Commercial"],
    pdfUrl: "/case-studies/Pembroke-Offices-AHU-Refurbishment-Case-Study.pdf",
  },
  {
    slug: "burlington-street-office-coil-replacement",
    title: "Burlington Street Office, Frost Coil Replacement",
    headline: "Frost Coil Replacement, Restricted Plantroom Access",
    sector: "Commercial",
    location: "London",
    image: "/burlington-street-office-case-study.webp",
    summary:
      "The frost coil at a Burlington Street commercial office suffered severe damage. BVS designed, manufactured, and installed a split-section replacement to overcome plantroom access constraints.",
    tags: ["Coil Replacement", "Commercial"],
    relevantIf: [
      "Your frost or heating coil has failed and needs replacing",
      "Restricted access means a standard single-piece coil cannot reach the plant room",
      "You need a solution that avoids structural modifications to the building",
    ],
    pdfUrl: "/case-studies/Burlington-Street-Office-Coil-Replacement-Case-Study.pdf",
    services: ["coil"],
  },
  {
    slug: "kingly-street-extract-fan-duct",
    title: "60 Kingly Street London, Extract Fan & Duct Installation",
    sector: "Commercial",
    location: "London",
    image: "/60-kingly-street-case-study.webp",
    summary:
      "BVS designed and installed a new extract fan and ductwork system at 60 Kingly Street, London, improving mechanical ventilation extraction performance for this commercial office property.",
    tags: ["Extract Fan", "Ductwork", "Commercial"],
    pdfUrl: "/case-studies/Kingly-Street-Office-Extract-Fan-Duct-Case-Study.pdf",
  },
  {
    slug: "newton-mearns-ahu-refurbishment-pipework",
    title: "Newton Mearns, Shopping Centre AHU Refurbishment & Gas Pipework",
    headline: "Shopping Centre AHU Refurbishment & Gas Pipework",
    sector: "Commercial",
    location: "Glasgow",
    image: "/newton-mearns-case-study.webp",
    summary:
      "BVS refurbished three weatherproof AHUs at Newton Mearns Shopping Centre and replaced a deteriorated mild-steel gas distribution network with 316-grade stainless steel pipework to IGEM UP 1 and 2.",
    tags: ["AHU Refurbishment", "Gas Pipework", "Commercial"],
    relevantIf: [
      "Your AHU serves a live retail or public environment that cannot close",
      "Belt-driven fans are overdue for upgrading",
      "Gas distribution infrastructure also needs a compliance review",
    ],
    pdfUrl: "/case-studies/The-Avenue-Newton-Mearns-AHU-Refurbishment-Pipework-Replacement-Case-Study.pdf",
    services: ["refurbishment"],
  },
  {
    slug: "disney-headquarters-ventilation-survey",
    title: "EU Disney Headquarters Hammersmith, Ventilation Survey",
    sector: "Commercial",
    location: "Hammersmith, London",
    image: "/disney-headquarters-case-study.webp",
    summary:
      "BVS conducted a full ventilation survey at the EU Disney Headquarters in Hammersmith, London, assessing AHU performance, air volumes, and system condition across the corporate campus.",
    tags: ["Ventilation Survey", "Commercial"],
    pdfUrl: "/case-studies/Disney-Headquarters-Hammersmith-Case-Study-Document-A4-Portrait-4.pdf",
  },
  {
    slug: "procook-westfield-ahu-controller-upgrade",
    title: "Procook Westfield, AHU Controller Upgrade",
    headline: "AHU Controller Upgrade, Westfield Retail Store",
    sector: "Commercial",
    location: "Westfield, London",
    image: "/procook-westfield-case-study.webp",
    summary:
      "The AHU at Procook's Westfield retail store had a failed fan motor and obsolete controls. BVS replaced the motor, installed a Trend BMS controller, and restored full climate control to the shop floor.",
    tags: ["Controller Upgrade", "Retail", "Trend"],
    relevantIf: [
      "AHU controls are obsolete or have failed and the system has stopped working",
      "You need automated scheduling aligned to your trading or operating hours",
      "Temperature control across the occupied space is unreliable",
    ],
    pdfUrl: "/case-studies/Case-Study-Procook-Westfield-AHU-Controls-5.pdf",
    services: ["controller"],
  },
  {
    slug: "toca-football-o2-ahu-refurbishment",
    title: "Toca Interactive Football O2 Arena, AHU Refurbishment",
    headline: "AHU Refurbishment, High-Footfall Venue",
    sector: "Commercial",
    location: "O2 Arena, London",
    image: "/toca-intereactive-arena-case-study.webp",
    summary:
      "BVS carried out an AHU refurbishment at the Toca Interactive Football facility at the O2 Arena, maintaining performance in a high-footfall sports entertainment environment.",
    tags: ["AHU Refurbishment", "Commercial"],
    relevantIf: [
      "Your venue has limited maintenance windows between events or trading hours",
      "Works must be programmed tightly around the operational calendar",
      "Asset life extension is preferred over full unit replacement",
    ],
    pdfUrl: "/case-studies/Toca-Football-O2-Arena-Case-Study-1-2.pdf",
    services: ["refurbishment"],
  },
  {
    slug: "concorde-simulator-ventilation",
    title: "Concorde Simulator, Ventilation Survey & Works",
    sector: "Commercial",
    image: "/concorde-project-case-study.webp",
    summary:
      "BVS carried out a ventilation survey and subsequent works on the Concorde simulator, a unique heritage environment requiring careful handling and specialist knowledge of the existing installation.",
    tags: ["Ventilation Survey", "Heritage"],
    pdfUrl: "/case-studies/Concorde-Project-Case-Study.pdf",
  },
  {
    slug: "car-dealership-farnborough-coil-replacement",
    title: "Car Dealership Farnborough, Heating Coil Replacement",
    headline: "Heating Coil & Pipework Replacement, Commercial Premises",
    sector: "Commercial",
    location: "Farnborough",
    image: "/car-dealership-case-study.webp",
    summary:
      "A car dealership in Farnborough required a full heating coil replacement in its AHU plant room. BVS sized, manufactured, and installed a replacement unit with full pipework and insulation to BSS6644:2011.",
    tags: ["Coil Replacement", "Commercial"],
    relevantIf: [
      "Your heating coil has failed or is consistently underperforming",
      "Associated pipework also needs replacing at the same time",
      "Works need to be completed to current installation standards",
    ],
    pdfUrl: "/case-studies/Car-Dealership-Coil-Replacement-Case-Study.pdf",
    services: ["coil"],
  },
  {
    slug: "pharmaceutical-lab-coil-replacement",
    title: "Pharmaceutical Manufacturer, AHU Coil Replacement",
    headline: "AHU Coil Replacement, Pharmaceutical Production",
    sector: "Manufacturing",
    location: "UK",
    image: "/pharmaceutical-lab-case-study.webp",
    summary:
      "BVS designed, manufactured, and installed a replacement AHU coil at a pharmaceutical manufacturing facility, meeting the strict process environment requirements of the site.",
    tags: ["Coil Replacement", "Pharmaceutical"],
    relevantIf: [
      "Your process environment has strict temperature and humidity tolerances",
      "Coil replacement must match original performance exactly",
      "Works need to be planned around production with minimum downtime",
    ],
    pdfUrl: "/case-studies/Case-Study-Pharmaceutical-Manufacturers.pdf",
    services: ["coil"],
  },
  {
    slug: "red-distillery-ahu-refurbishment",
    title: "Red English Group Distillery, AHU Refurbishment",
    headline: "AHU Refurbishment, Active Production Facility",
    sector: "Manufacturing",
    location: "UK",
    image: "/red-english-group-distillery-case-study.webp",
    summary:
      "BVS refurbished the AHU at Red English Group's distillery facility, restoring reliable ventilation performance in an active production environment.",
    tags: ["AHU Refurbishment", "Manufacturing"],
    relevantIf: [
      "Your environment has specific temperature or humidity requirements tied to production",
      "Shutdown windows need to be planned around a production schedule",
      "The facility remains operational during the works",
    ],
    pdfUrl: "/case-studies/Red-Distillery-Case-Study-2.pdf",
    services: ["refurbishment"],
  },
];
