export const sectorData = {
  education: {
    title: "Education",
    headline: "AHU & Ventilation Services for Schools, Colleges & Universities",
    description: "BVS delivers AHU refurbishment, EC fan upgrades, and ventilation maintenance for education sector buildings across the UK.",
    intro: "Educational buildings rely on properly maintained ventilation to support occupant health, learning environments, and compliance with CIBSE and HTM guidance. We work around term times and holiday periods to minimise disruption.",
    services: [
      "AHU condition surveys and reports",
      "Refurbishment and life extension",
      "EC fan upgrades for energy savings",
      "Coil replacement and repair",
      "Planned preventive maintenance",
      "Validation testing to CIBSE guidelines",
    ],
    clients: "We have delivered projects across secondary schools, sixth form colleges, universities, and specialist educational facilities - including sites within the NHS estate.",
  },
  defence: {
    title: "Defence",
    headline: "Ventilation & AHU Services for Defence and Government Facilities",
    description: "Secure, compliant ventilation solutions for MoD, government, and defence-sector buildings. BVS is experienced working within strict access and clearance requirements.",
    intro: "Defence sites and government facilities require contractors who understand the requirements around security vetting, restricted access, and uncompromising compliance standards. We have experience working within these environments.",
    services: [
      "AHU surveys and condition reports",
      "Refurbishment and component replacement",
      "EC fan and controller upgrades",
      "Ducting repair and replacement",
      "Compliance and validation documentation",
      "Planned and reactive maintenance",
    ],
    clients: "We have worked on government and quasi-government sites requiring enhanced security procedures and strict adherence to programme and access requirements.",
  },
  hotel: {
    title: "Hotels",
    headline: "AHU & HVAC Services for Hotels",
    description: "Maintaining air quality and comfort in hotels - with minimum disruption to operations.",
    intro: "In hotel environments, ventilation failure directly affects guest experience and revenue. We plan all works to minimise disruption — working around occupancy, scheduling overnight or out-of-hours where required.",
    services: [
      "AHU refurbishment and life extension",
      "EC fan retrofits for energy and noise reduction",
      "Coil replacement to restore HVAC performance",
      "Chiller plant and pipework support",
      "Planned maintenance programmes",
      "Emergency call-out and reactive repair",
    ],
    clients: "Clients include Marriott, Warner Hotels, IHG, and Travelodge.",
  },
  "leisure-centre": {
    title: "Leisure Centres",
    headline: "AHU & Ventilation for Leisure Centres and Aquatic Facilities",
    description: "High-humidity AHU and ventilation management for leisure centres, swimming pools, and sports facilities. Specialist knowledge of corrosion-resistant equipment and humidity control.",
    intro: "Leisure centres and pool halls present unique challenges - high humidity, corrosive environments, and strict air quality requirements. We specify and install equipment built for these conditions, not standard commercial units adapted to cope.",
    services: [
      "Pool hall AHU survey and assessment",
      "Corrosion-resistant component sourcing",
      "Full AHU refurbishment or replacement",
      "Heat recovery coil installation",
      "Humidity control validation",
      "Planned maintenance and reactive support",
    ],
    clients: "We have worked across local authority and private leisure centres, aquatic facilities, and sports complexes across the UK.",
  },
  hospital: {
    title: "Hospital & Healthcare",
    headline: "Critical Environment Ventilation for NHS and Private Healthcare",
    description: "AHU refurbishment, validation surveys, and EC fan upgrades for hospitals and healthcare buildings. Compliant with HTM 03-01 and CIBSE guidance.",
    intro: "Healthcare ventilation is subject to some of the most stringent standards in the built environment. HTM 03-01 compliance, infection control requirements, and 24/7 occupancy mean there is no margin for error. We understand these requirements and manage all works accordingly.",
    services: [
      "HTM 03-01 compliant validation surveys",
      "AHU refurbishment in critical environments",
      "EC fan upgrades with BMS integration",
      "Coil replacement to restore performance",
      "HEPA filter housing upgrades",
      "Documented compliance reporting",
    ],
    clients: "We work with NHS Trusts, private hospital operators, and specialist healthcare facilities - including Moorfields Eye Hospital.",
  },
  retail: {
    title: "Retail",
    headline: "Commercial HVAC for Retail Parks, Supermarkets and Shopping Centres",
    description: "Planned and reactive AHU and ventilation services for retail environments - managed around trading hours with minimum disruption.",
    intro: "Retail sites need reliable HVAC to maintain comfortable shopping environments and comply with workplace regulations. We understand the commercial pressures of retail - works are planned around trading hours, with reactive support available when needed.",
    services: [
      "AHU condition surveys and reports",
      "Refurbishment to extend asset life",
      "EC fan upgrades to reduce operating costs",
      "Coil replacement and repair",
      "Planned maintenance programmes",
      "Out-of-hours emergency response",
    ],
    clients: "We have delivered projects for supermarket chains, retail parks, and shopping centre operators across the UK.",
  },
};
